# Generated by Django 5.0.3 on 2024-06-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='house_number',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street',
            field=models.CharField(default='Unknown Street', max_length=255),
        ),
        migrations.AddField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(default=1),
        ),
    ]
