# Generated by Django 5.0.3 on 2024-06-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagement', '0004_remove_table_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
