# Generated by Django 5.0.3 on 2024-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagement', '0005_table_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_days',
            field=models.ManyToManyField(to='RestaurantManagement.openingday'),
        ),
    ]
