# Generated by Django 5.0.6 on 2024-06-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagement', '0008_remove_restaurant_menu_menuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
