# Generated by Django 5.0.6 on 2024-06-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagement', '0009_delete_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Stadt', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street',
            field=models.CharField(default='Strasse', max_length=255),
        ),
    ]
