# Generated by Django 5.0.6 on 2024-06-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagement', '0011_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
